language: python
python:
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=postero postero/manage.py test postero
after_success:
  coveralls
