language: python
python:
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=linkbox linkbox/manage.py test linkbox
after_success:
  coveralls
